// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/beecool-cocktail/application-backend/domain"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// CocktailPhotoMySQLRepository is an autogenerated mock type for the CocktailPhotoMySQLRepository type
type CocktailPhotoMySQLRepository struct {
	mock.Mock
}

// DeleteByCocktailIDTx provides a mock function with given fields: ctx, tx, id
func (_m *CocktailPhotoMySQLRepository) DeleteByCocktailIDTx(ctx context.Context, tx *gorm.DB, id int64) error {
	ret := _m.Called(ctx, tx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64) error); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByIDTx provides a mock function with given fields: ctx, tx, id
func (_m *CocktailPhotoMySQLRepository) DeleteByIDTx(ctx context.Context, tx *gorm.DB, id int64) error {
	ret := _m.Called(ctx, tx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, int64) error); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// QueryCoverPhotoByCocktailId provides a mock function with given fields: ctx, id
func (_m *CocktailPhotoMySQLRepository) QueryCoverPhotoByCocktailId(ctx context.Context, id int64) (string, error) {
	ret := _m.Called(ctx, id)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, int64) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryPhotoById provides a mock function with given fields: ctx, id
func (_m *CocktailPhotoMySQLRepository) QueryPhotoById(ctx context.Context, id int64) (domain.CocktailPhoto, error) {
	ret := _m.Called(ctx, id)

	var r0 domain.CocktailPhoto
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.CocktailPhoto); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.CocktailPhoto)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryPhotosByCocktailId provides a mock function with given fields: ctx, id
func (_m *CocktailPhotoMySQLRepository) QueryPhotosByCocktailId(ctx context.Context, id int64) ([]domain.CocktailPhoto, error) {
	ret := _m.Called(ctx, id)

	var r0 []domain.CocktailPhoto
	if rf, ok := ret.Get(0).(func(context.Context, int64) []domain.CocktailPhoto); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CocktailPhoto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreTx provides a mock function with given fields: ctx, tx, c
func (_m *CocktailPhotoMySQLRepository) StoreTx(ctx context.Context, tx *gorm.DB, c *domain.CocktailPhoto) error {
	ret := _m.Called(ctx, tx, c)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *domain.CocktailPhoto) error); ok {
		r0 = rf(ctx, tx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTx provides a mock function with given fields: ctx, tx, c
func (_m *CocktailPhotoMySQLRepository) UpdateTx(ctx context.Context, tx *gorm.DB, c *domain.CocktailPhoto) (int64, error) {
	ret := _m.Called(ctx, tx, c)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *domain.CocktailPhoto) int64); ok {
		r0 = rf(ctx, tx, c)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB, *domain.CocktailPhoto) error); ok {
		r1 = rf(ctx, tx, c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
