// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CocktailAccountUsecase is an autogenerated mock type for the CocktailAccountUsecase type
type CocktailAccountUsecase struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx, limit, page
func (_m *CocktailAccountUsecase) GetAll(ctx context.Context, limit int, page int) {
	_m.Called(ctx, limit, page)
}
