// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/beecool-cocktail/application-backend/domain"
	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// CocktailStepMySQLRepository is an autogenerated mock type for the CocktailStepMySQLRepository type
type CocktailStepMySQLRepository struct {
	mock.Mock
}

// StoreTx provides a mock function with given fields: ctx, tx, c
func (_m *CocktailStepMySQLRepository) StoreTx(ctx context.Context, tx *gorm.DB, c *domain.CocktailStep) error {
	ret := _m.Called(ctx, tx, c)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *domain.CocktailStep) error); ok {
		r0 = rf(ctx, tx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
