// Code generated by mockery v2.30.16. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/beecool-cocktail/application-backend/domain"
	mock "github.com/stretchr/testify/mock"
)

// CocktailStepUsecase is an autogenerated mock type for the CocktailStepUsecase type
type CocktailStepUsecase struct {
	mock.Mock
}

// Store provides a mock function with given fields: ctx, c
func (_m *CocktailStepUsecase) Store(ctx context.Context, c *domain.CocktailStep) error {
	ret := _m.Called(ctx, c)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CocktailStep) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCocktailStepUsecase creates a new instance of CocktailStepUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCocktailStepUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CocktailStepUsecase {
	mock := &CocktailStepUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
