// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/beecool-cocktail/application-backend/domain"
	mock "github.com/stretchr/testify/mock"
)

// CommandUsecase is an autogenerated mock type for the CommandUsecase type
type CommandUsecase struct {
	mock.Mock
}

// Store provides a mock function with given fields: ctx, c
func (_m *CommandUsecase) Store(ctx context.Context, c *domain.Command) error {
	ret := _m.Called(ctx, c)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Command) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Undo provides a mock function with given fields: ctx, id
func (_m *CommandUsecase) Undo(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
