// Code generated by mockery v2.30.16. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/beecool-cocktail/application-backend/domain"
	mock "github.com/stretchr/testify/mock"
)

// CommandUsecase is an autogenerated mock type for the CommandUsecase type
type CommandUsecase struct {
	mock.Mock
}

// Store provides a mock function with given fields: ctx, c
func (_m *CommandUsecase) Store(ctx context.Context, c *domain.Command) error {
	ret := _m.Called(ctx, c)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Command) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Undo provides a mock function with given fields: ctx, id
func (_m *CommandUsecase) Undo(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCommandUsecase creates a new instance of CommandUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommandUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommandUsecase {
	mock := &CommandUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
