// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DBTransactionRepository is an autogenerated mock type for the DBTransactionRepository type
type DBTransactionRepository struct {
	mock.Mock
}

// Transaction provides a mock function with given fields: _a0
func (_m *DBTransactionRepository) Transaction(_a0 func(interface{}) error) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(func(interface{}) error) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
