// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/beecool-cocktail/application-backend/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserFileRepository is an autogenerated mock type for the UserFileRepository type
type UserFileRepository struct {
	mock.Mock
}

// SaveAsWebp provides a mock function with given fields: ctx, ui
func (_m *UserFileRepository) SaveAsWebp(ctx context.Context, ui *domain.UserImage) error {
	ret := _m.Called(ctx, ui)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserImage) error); ok {
		r0 = rf(ctx, ui)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
