basePath: /api
definitions:
  GetPopularCocktailListRequest:
    properties:
      page:
        example: 1
        format: int64
        type: integer
        x-go-name: Page
      page_size:
        example: 10
        format: int64
        type: integer
        x-go-name: PageSize
    required:
    - page
    - page_size
    type: object
    x-go-package: github.com/beecool-cocktail/application-backend/viewmodels
  GetPopularCocktailListResponse:
    properties:
      popular_cocktail_list:
        items:
          $ref: '#/definitions/PopularCocktailList'
        type: array
        x-go-name: PopularCocktailList
      total:
        format: int64
        type: integer
        x-go-name: Total
    type: object
    x-go-package: github.com/beecool-cocktail/application-backend/viewmodels
  GetUserInfoResponse:
    properties:
      email:
        type: string
        x-go-name: Email
      number_of_collection:
        format: int64
        type: integer
        x-go-name: NumberOfCollection
      number_of_post:
        format: int64
        type: integer
        x-go-name: NumberOfPost
      photo:
        type: string
        x-go-name: Photo
      user_id:
        format: int64
        type: integer
        x-go-name: UserID
      user_name:
        type: string
        x-go-name: Name
    type: object
    x-go-package: github.com/beecool-cocktail/application-backend/viewmodels
  GoogleAuthenticateRequest:
    properties:
      code:
        type: string
        x-go-name: Code
    type: object
    x-go-package: github.com/beecool-cocktail/application-backend/viewmodels
  GoogleAuthenticateResponse:
    properties:
      token:
        type: string
        x-go-name: Token
    type: object
    x-go-package: github.com/beecool-cocktail/application-backend/viewmodels
  LogoutRequest:
    properties:
      user_id:
        format: int64
        type: integer
        x-go-name: UserID
    type: object
    x-go-package: github.com/beecool-cocktail/application-backend/viewmodels
  PopularCocktailList:
    properties:
      cocktail_id:
        format: int64
        type: integer
        x-go-name: CocktailID
      created_date:
        type: string
        x-go-name: CreatedDate
      photo:
        type: string
        x-go-name: Photo
      title:
        type: string
        x-go-name: Title
    type: object
    x-go-package: github.com/beecool-cocktail/application-backend/viewmodels
  ResponseData:
    properties:
      data:
        type: object
        x-go-name: Data
      error_code:
        type: string
        x-go-name: ErrorCode
      error_message:
        type: string
        x-go-name: ErrorMessage
    type: object
    x-go-package: github.com/beecool-cocktail/application-backend/viewmodels
host: localhost:6969
info:
  description: This is api server
  title: api server
  version: "0.1"
paths:
  /cocktails:
    post:
      description: Get popular cocktail list order by create date.
      operationId: popularCocktailListRequest
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/GetPopularCocktailListRequest'
      responses:
        "200":
          $ref: '#/responses/popularCocktailListResponse'
        "400":
          description: ' bad request'
        "401":
          description: ' unauthorized'
        "404":
          description: ' item not found'
        "500":
          description: ' internal error'
      summary: Get popular cocktail list
      tags:
      - cocktail
  /google-authenticate:
    post:
      description: Use Code to exchange access token.
      operationId: googleAuthenticateRequest
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/GoogleAuthenticateRequest'
      responses:
        "201":
          $ref: '#/responses/googleAuthenticateResponse'
      summary: Get access token.
      tags:
      - login
  /google-login:
    get:
      description: Will redirect with authorization code.
      operationId: googleLogin
      responses:
        "307":
          description: ' redirect'
      summary: Login with google OAuth2
      tags:
      - login
  /user/info:
    get:
      description: Get user id, name, email, numberOfPost, numberOfCollection and
        photo.
      operationId: info
      responses:
        "200":
          $ref: '#/responses/getUserInfoResponse'
      security:
      - Bearer:
        - apiKey
      summary: Get user information.
      tags:
      - user
  /user/logout:
    post:
      description: make token invalid.
      operationId: logoutRequest
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/LogoutRequest'
      responses: {}
      summary: User logout.
      tags:
      - user
responses:
  googleAuthenticateResponse:
    description: ""
    schema:
      $ref: '#/definitions/GoogleAuthenticateResponse'
  popularCocktailListResponse:
    description: ""
    schema:
      $ref: '#/definitions/GetPopularCocktailListResponse'
schemes:
- http
- https
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
