name: Go

on:
  [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Update apt-get
      run: sudo apt-get update

    - name: Add build-base
      run: sudo apt-get install build-base

    - name: Add libwebp-dev
      run: sudo apt-get install libwebp-dev

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
