name: deploy to Cloud Run

on:
  create:
    tags:
    - v*

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REPO_NAME: backend-repo
  IMAGE_NAME: application-backend
  RUN_REGION: asia-east1
  TAG: release

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true
        
    # Print gcloud info
    - name: Info
      run: gcloud info

    # Build and push image to Google Artifact Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --config ./cloudbuild.yml \
          --substitutions=REVISION_ID=${GITHUB_SHA},_REPO_NAME=${REPO_NAME},_IMAGE_NAME=${IMAGE_NAME},_TAG=${TAG}

    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy "${IMAGE_NAME}" \
          --region "$RUN_REGION" \
          --image "asia-east1-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${TAG}" \
          --platform "managed" \
          --allow-unauthenticated
          
