name: deploy to Compute Engine

on:
  create:
    tags:
      - v*

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Update apt-get
        run: sudo apt-get update

      - name: Add build-essential
        run: sudo apt-get install build-essential

      - name: Add libwebp-dev
        run: sudo apt-get install libwebp-dev

      - name: Test
        run: go test -v ./...

      - name: executing remote ssh commands via ssh key
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd backend-application
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER_NAME }} --password-stdin
            docker-compose -f docker-compose-dev.yml pull
            docker-compose -f docker-compose-dev.yml up -d