name: deploy to Cloud Run

on:
  push:
    branches: [ deploy-to-compute-engine ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CONFIG_FILE: serviceConfigDev.json
  REPO_NAME: backend-repo
  IMAGE_NAME: application-backend
  RUN_REGION: asia-east1
  TAG: release

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: go test -v ./...

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: blawhi2435/whispering-corner
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/backend-application"

      - name: executing remote ssh commands via ssh key
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd backend-application
            docker-compose pull
            docker-compose up -d