name: update docker hub

on:
  push:
    branches:
      - 'beta/**'
      - 'master'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CONFIG_FILE: serviceConfigDev.json
  TAGS: v0.12.3,latest

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Update apt-get
        run: sudo apt-get update

      - name: Add build-essential
        run: sudo apt-get install build-essential

      - name: Add libwebp-dev
        run: sudo apt-get install libwebp-dev

      - name: Test
        run: go test -v ./...

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: blawhi2435/whispering-corner
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ env.TAGS }}
          dockerfile: Dockerfile